{
    "page_warn":{
        "page_type":"scroll",
        "page_title":"微信支付",
        "title":"账户收发群红包行为存在异常，常见于红包赌博场景，请查看示例并自查使用情况",
        "sub_title":"",
        "promise":[
            {
                "type":"img",
                "id":0,
                "title":"伪装游戏实为赌博",
                "sub_title":"以获利为目的，按照约定的规则抢发红包或转账",
                "imgUrl":"/touch/wechat/pay/taiben/images/behavior32_1.png",
                "is_confirm":true
            },
            {
                "type":"img",
                "id":1,
                "title":"微信红包赌局押注",
                "sub_title":"猜红包大小、以红包金额作为押注",
                "imgUrl":"/touch/wechat/pay/taiben/images/behavior32_2.png",
                "is_confirm":true
            },
            {
                "type":"img",
                "id":2,
                "title":"玩法繁多难以甄别",
                "sub_title":"其他以红包、转账形式进行赌博的行为",
                "imgUrl":"/touch/wechat/pay/taiben/images/behavior32_3.png",
                "is_confirm":true
            }
        ],
        "confirm_options":[
            {
                "type":"checkbox",
                "text":"我已知悉以上提醒，明确本次交易与以上行为无关，并授权贵司进行相关信息留存。"
            }
        ],
        "tips":{
            "type":"bottom_text_tip",
            "content":[
                {
                    "type":"string",
                    "text":"若有疑问，可点击这里"
                },
                {
                    "type":"button",
                    "text":"联系客服",
                    "action":"ai",
                    "ai_code":"faq_1000002_l4_4024656_H5FK"
                },
                {
                    "type":"string",
                    "text":""
                }
            ]
        },
        "primary_button":"放弃支付",
        "sub_button":"继续支付"
    },
    "page_success":{
        "primary_button":"关闭",
        "page_title":"微信支付",
        "tips":"你已明确交易行为不存在违规风险，可重新发起支付",
        "title":"操作成功"
    },
    "page_error":{
        "primary_button":"关闭",
        "page_title":"微信支付",
        "title":"操作失败",
        "tips":"操作失败，请重新尝试",
        "bottom_tip":"联系客服"
    },
    "page_no_permission":{
        "page_title":"微信支付",
        "title":"暂无权限访问该页面",
        "primary_button":"确认"
    },
    "page_repeat":{
        "page_title":"微信支付",
        "title":"你已明确核实交易风险，可继续发起支付，请勿重复提交",
        "primary_button":"确认"
    }
}



{
        "page_warn":{
            "page_type":"check",
            "page_title":"微信支付",
            "title":"本次交易可能存在风险，为了你的资金安全，请确认如下内容，谨慎判断是否继续支付",
            "sub_title":"",
            "check":{
                "1":{
                    "pid":[
    
                    ],
                    "type":"checkbox",
                    "title":"该笔交易付款成功后资金无法退回，请谨防刷单兼职、贷款提额、高额返利等网络骗局",
                    "sub_title":"",
                    "imgUrl":"",
                    "single":true,
                    "options":[
                        {
                            "text":"我已确认无风险",
                            "select":false,
                            "child":[
                                3,
                                4
                            ]
                        }
                    ],
                    "is_confirm":false
                },
                "2":{
                    "pid":[
    
                    ],
                    "type":"checkbox",
                    "title":"请确认交易发起人身份：",
                    "sub_title":"",
                    "imgUrl":"",
                    "single":true,
                    "options":[
                        {
                            "text":"我是未成年",
                            "select":false,
                            "child":[
                                3
                            ]
                        },
                        {
                            "text":"我是成年人",
                            "select":false,
                            "child":[
                                4
                            ]
                        }
                    ],
                    "is_confirm":false
                },
                "3":{
                    "pid":[
                        1,
                        2
                    ],
                    "type":"checkbox",
                    "title":"请确认是否本人自愿发起交易",
                    "sub_title":"",
                    "imgUrl":"",
                    "single":true,
                    "options":[
                        {
                            "text":"已明确交易原因，使用家长微信自愿发起交易",
                            "select":false,
                            "tipText":"未避免未成年非理性网络消费，确保家长对该笔交易知情，请家长进行身份验证"
                        },
                        {
                            "text":"未明确交易目的，在他人引导下使用家长微信发起交易",
                            "select":false,
                            "tipText":"未成年人缺乏防范意识及甄别能力，交易需由家长进行确认，不要与陌生人私下交易，随意进行转账充值等操作，避免造成不必要的损失"
                        }
                    ],
                    "is_confirm":false
                },
                "4":{
                    "pid":[
                        1,
                        2
                    ],
                    "type":"checkbox",
                    "title":"请确认是否本人自愿发起交易",
                    "sub_title":"",
                    "imgUrl":"",
                    "single":true,
                    "options":[
                        {
                            "text":"是我本人自愿发起交易",
                            "select":false,
                            "tipText":"为确保本人操作，请微信支付实名本人进行身份核验"
                        },
                        {
                            "text":"非本人意愿，在他人引导下发起交易",
                            "select":false,
                            "tipText":"付款前请谨慎核实交易目的，切勿轻信他人，付款成功后资金无法退回，若确认本人自愿支付，请微信支付实名本人进行身份核验"
                        },
                        {
                            "text":"亲友不会操作，帮亲友代付",
                            "select":false,
                            "tipText":"为确保亲友授权进行支付，请微信支付实名本人进行身份核验"
                        }
                    ],
                    "is_confirm":false
                }
            },
            "confirm_options":[
                {
                    "type":"checkbox",
                    "text":"我已知悉以上行为存在风险，明确本次交易与上述行为无关"
                }
            ],
            "tips":{
                "type":"bottom_text_tip",
                "content":[
                    {
                        "type":"string",
                        "text":"若有疑问，可点击这里"
                    },
                    {
                        "type":"button",
                        "text":"联系客服",
                        "action":"ai",
                        "ai_code":"faq_1000002_l4_4024656_H5FK"
                    },
                    {
                        "type":"string",
                        "text":""
                    }
                ]
            },
            "primary_button":"放弃支付",
            "sub_button":"继续支付"
        },
        "page_success":{
            "primary_button":"确认",
            "page_title":"微信支付",
            "tips":"你已明确核实交易风险，可继续发起支付",
            "title":"关闭本页，重新登录"
        },
        "page_error":{
            "primary_button":"关闭",
            "page_title":"微信支付",
            "title":"操作失败，请重试",
            "bottom_tip":"联系客服"
        },
        "page_no_permission":{
            "page_title":"微信支付",
            "title":"暂无权限访问该页面",
            "primary_button":"确认"
        },
        "page_repeat":{
            "page_title":"微信支付",
            "title":"你已明确核实交易风险，可继续发起支付，请勿重复提交",
            "primary_button":"确认"
        }
    }
    



    {
        "page_warn":{
            "page_type":"topic",
            "page_title":"微信支付",
            "title":"本次交易可能存在风险，为了你的资金安全，请完善交易信息，谨慎判断是否继续支付",
            "sub_title":"",
            "deep":3,
            "topic":{
                "1":{
                    "dep":1,
                    "title":"因什么原因支付该笔资金给对方",
                    "list":[
                        {
                            "title":"缴纳刷单、兼职、返利、抽奖费用等",
                            "listid":2,
                            "select":false
                        },
                        {
                            "title":"购买游戏道具、软件、虚拟币充值等、直播礼物等产品",
                            "listid":4,
                            "select":false
                        },
                        {
                            "title":"代付购买实物商品",
                            "listid":5,
                            "select":false
                        },
                        {
                            "title":"通过视频共享等方式展示二维码购买商品",
                            "listid":6,
                            "select":false
                        },
                        {
                            "title":"购买礼品卡、电话充值卡、加油卡或线上缴纳电费",
                            "listid":7,
                            "select":false
                        }
                    ]
                },
                "2":{
                    "dep":2,
                    "title":"请选择兼职刷单类型：",
                    "list":[
                        {
                            "title":"下载刷单点赞软件或进入刷单网站，充值并完成任务",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"在 QQ ／微信等社交软件上领取任务，并完成支付",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"去购物平台下单截图，在其他渠道付款",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"其他兼职工作（家教、模特、快递外卖、手工等）",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"其他类型",
                            "listid":8,
                            "select":false
                        }
                    ]
                },
                "4":{
                    "dep":2,
                    "title":"请选择具体购买虚拟产品信息：",
                    "list":[
                        {
                            "title":"软件/应用（app)",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"虚拟币充值",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"直播间刷礼物",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"游戏道具装备",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"其他商品",
                            "listid":8,
                            "select":false
                        }
                    ]
                },
                "5":{
                    "dep":2,
                    "title":"请选择代付购买实物产品信息：",
                    "list":[
                        {
                            "title":"服饰",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"生活用品",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"数码产品",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"宠物",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"办证",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"演唱会/景点门票",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"其他商品",
                            "listid":8,
                            "select":false
                        }
                    ]
                },
                "6":{
                    "dep":2,
                    "title":"请选择视频共享购买商品信息：",
                    "list":[
                        {
                            "title":"游戏装备",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"代练服务",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"游戏充值",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"帐号买卖",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"其他商品",
                            "listid":8,
                            "select":false
                        }
                    ]
                },
                "7":{
                    "dep":2,
                    "title":"请选择充值卡具体产品信息：",
                    "list":[
                        {
                            "title":"不记名购物卡",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"超市/商店礼品卡",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"汽车加油卡",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"话费/流量充值卡",
                            "listid":8,
                            "select":false
                        },
                        {
                            "title":"其他商品",
                            "listid":8,
                            "select":false
                        }
                    ]
                },
                "8":{
                    "dep":3,
                    "isLast":true,
                    "title":"获取对方信息的渠道：",
                    "list":[
                        {
                            "title":"QQ",
                            "listid":null,
                            "select":false
                        },
                        {
                            "title":"微信",
                            "listid":null,
                            "select":false
                        },
                        {
                            "title":"电话/短信",
                            "listid":null,
                            "select":false
                        },
                        {
                            "title":"相关网站",
                            "listid":null,
                            "select":false
                        },
                        {
                            "title":"第三方app（闲鱼、转转、抖音、快手、小红书）",
                            "listid":null,
                            "select":false
                        },
                        {
                            "title":"微博",
                            "listid":null,
                            "select":false
                        },
                        {
                            "title":"面对面告知",
                            "listid":null,
                            "select":false
                        },
                        {
                            "title":"其他渠道",
                            "listid":null,
                            "select":false
                        }
                    ]
                }
            },
            "confirm_options":[
    
            ],
            "tips":{
                "type":"bottom_text_tip",
                "content":[
                    {
                        "type":"string",
                        "text":"若有疑问，可点击这里"
                    },
                    {
                        "type":"button",
                        "text":"联系客服",
                        "action":"ai",
                        "ai_code":"faq_1000002_l4_4024656_H5FK"
                    },
                    {
                        "type":"string",
                        "text":""
                    }
                ]
            },
            "primary_button":"放弃支付",
            "sub_button":"继续支付"
        },
        "page_confirm":[
            {
                "title":"请谨慎确认交易风险",
                "text":"警惕网络刷单骗局，诈骗分子以任务未完成诱导消费者继续刷单为由实施诈骗，切勿相信刷完即可返佣，系统被冻结等话语，谨防诈骗。"
            },
            {
                "title":"请谨慎确认交易风险",
                "text":"不法分子打着低价售卖游戏物品或软件等幌子，诱导消费者付款后拉黑，请谨慎与他人在网络上进行私下交易。"
            },
            {
                "title":"请谨慎确认交易风险",
                "text":"不法分子冒充亲戚朋友，诱导代付购买数码等商品，提供商家二维码方式收款后拉黑好友，建议通过电话、视频等方式核实对方身份后再付款，谨防诈骗。"
            },
            {
                "title":"请谨慎确认交易风险",
                "text":"不法分子专门在未成年人聚集的游戏群、短视频平台、贴吧等发布虚假信息，骗子以“打折”、“返利”、“免费”等为诱饵，诱导消费者出示付款码支付，从而实施诈骗。"
            },
            {
                "title":"请谨慎确认交易风险",
                "text":"诈骗分子会以支付不扣费或支付会退还等理由，诱导消费者为其在平台购买购物卡、礼品卡等商品后拉黑。消费者线上交易建议要看清交易商品，切勿轻信支付不扣费等话语，被骗子诱骗购买虚拟卡类商品。"
            }
        ],
        "page_success":{
            "primary_button":"确认",
            "page_title":"微信支付",
            "tips":"你已明确核实交易风险，可继续发起支付",
            "title":"关闭本页，重新登录"
        },
        "page_error":{
            "primary_button":"关闭",
            "page_title":"微信支付",
            "title":"操作失败，请重试",
            "bottom_tip":"联系客服"
        },
        "page_no_permission":{
            "page_title":"微信支付",
            "title":"暂无权限访问该页面",
            "primary_button":"确认"
        },
        "page_repeat":{
            "page_title":"微信支付",
            "title":"你已明确核实交易风险，可继续发起支付，请勿重复提交",
            "primary_button":"确认"
        }
    }
    